# This workflow is for production builds, main branch builds, etc.

# Project: Mercy (https://github.com/azazelm3dj3d/mercy)
# Author(s): azazelm3dj3d (https://github.com/azazelm3dj3d)
# License: BSD 2-Clause

name: Mercy Status (Main)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose