# This workflow is for production builds, main branch builds, etc.

# Project: Mercy (https://github.com/azazelm3dj3d/mercy)
# Author(s): azazelm3dj3d (https://github.com/azazelm3dj3d)
# License: BSD 2-Clause

name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  runs-on: ubuntu-latest

  check:
      steps:
      - uses: actions/checkout@v3
      - name: Check
        run: cargo check

  test:
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test

  build:
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose